# Generated by Django 5.1.7 on 2025-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0002_alumno_apellido_paterno_alter_alumno_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="apellido_paterno",
        ),
        migrations.AlterField(
            model_name="alumno",
            name="nombre",
            field=models.CharField(default="", max_length=200),
        ),
    ]
