# Generated by Django 5.1.7 on 2025-03-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0003_remove_alumno_apellido_paterno_alter_alumno_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="id",
        ),
        migrations.AddField(
            model_name="alumno",
            name="id_alumno",
            field=models.BigAutoField(default="", primary_key=True, serialize=False),
        ),
    ]
