# Generated by Django 5.1.7 on 2025-03-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0004_remove_alumno_id_alumno_id_alumno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="id_alumno",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
