# Generated by Django 5.1.7 on 2025-03-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0005_alter_alumno_id_alumno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                ("id_alumno", models.BigAutoField(primary_key=True, serialize=False)),
                ("matriculo_alumno", models.CharField(default="", max_length=200)),
                ("nombre", models.CharField(default="", max_length=200)),
                ("apellido_paterno", models.CharField(default="", max_length=200)),
                ("apellido_materno", models.CharField(default="", max_length=200)),
                ("telefono", models.IntegerField(default=0, max_length=10)),
                ("correo_electronico", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="alumno",
            name="apellido_materno",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="alumno",
            name="apellido_paterno",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="alumno",
            name="correo_electronico",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="alumno",
            name="genero",
            field=models.CharField(default="indefinida", max_length=10),
        ),
        migrations.AddField(
            model_name="alumno",
            name="grado",
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="alumno",
            name="grupo",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="alumno",
            name="matricula",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="alumno",
            name="telefono",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
