# Generated by Django 5.1.7 on 2025-03-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0006_tutor_alumno_apellido_materno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="imagen_alumno",
            field=models.ImageField(default="", upload_to="imagenes_alumnos/"),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="grado",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="telefono",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefono",
            field=models.IntegerField(default=0),
        ),
    ]
