# Generated by Django 5.1.7 on 2025-03-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0007_alumno_imagen_alumno_alter_alumno_grado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="matricula",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
