# Generated by Django 5.1.7 on 2025-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0008_alter_alumno_matricula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="imagen_alumno",
        ),
        migrations.AlterField(
            model_name="alumno",
            name="apellido_materno",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="apellido_paterno",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="correo_electronico",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="genero",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="grado",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="grupo",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="matricula",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="telefono",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="apellido_materno",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="apellido_paterno",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="correo_electronico",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="matriculo_alumno",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefono",
            field=models.IntegerField(),
        ),
    ]
