# Generated by Django 5.1.7 on 2025-03-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0009_remove_alumno_imagen_alumno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="imagen_alumno",
            field=models.ImageField(null=True, upload_to="imagenes_alumnos/"),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="apellido_materno",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="apellido_paterno",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="correo_electronico",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="genero",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="grado",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="grupo",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="matricula",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="nombre",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="telefono",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="apellido_materno",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="apellido_paterno",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="correo_electronico",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="matriculo_alumno",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nombre",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefono",
            field=models.IntegerField(null=True),
        ),
    ]
