# Generated by Django 5.1.7 on 2025-03-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registros",
            "0010_alumno_imagen_alumno_alter_alumno_apellido_materno_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="genero",
            field=models.CharField(
                choices=[("H", "Hombre"), ("M", "Mujer")], max_length=1, null=True
            ),
        ),
    ]
