# Generated by Django 5.1.7 on 2025-04-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0011_alter_alumno_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
