# Generated by Django 5.1.7 on 2025-04-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0012_alumno_qr_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor",
            old_name="apellido_materno",
            new_name="apellido_materno_tutor",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="apellido_paterno",
            new_name="apellido_paterno_tutor",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="correo_electronico",
            new_name="correo_electronico_tutor",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="nombre",
            new_name="nombre_tutor",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="telefono",
            new_name="telefono_tutor",
        ),
    ]
