# Generated by Django 5.1.7 on 2025-04-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registros",
            "0013_rename_apellido_materno_tutor_apellido_materno_tutor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor",
            old_name="id_alumno",
            new_name="id_tutor",
        ),
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                ("id_registro", models.BigAutoField(primary_key=True, serialize=False)),
                ("entrada_hora_fecha", models.DateTimeField(auto_now_add=True)),
                ("salida_hora_fecha", models.DateTimeField()),
                ("entrada_registrada", models.BooleanField(default=True)),
                ("salida_registrada", models.BooleanField(default=False)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="registros.alumno",
                    ),
                ),
            ],
        ),
    ]
