# Generated by Django 5.1.7 on 2025-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0014_rename_id_alumno_tutor_id_tutor_registroasistencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroasistencia",
            name="salida_registrada",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
