# Generated by Django 5.1.7 on 2025-04-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0016_alter_registroasistencia_salida_hora_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
