# Generated by Django 5.1.7 on 2025-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0017_alter_alumno_apellido_materno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="genero",
            field=models.CharField(
                choices=[
                    ("", "Seleccionar un genero:"),
                    ("H", "Hombre"),
                    ("M", "Mujer"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
